### ISSUE TITLE
Shareable Insights

### ISSUE THREAD

**Issue by bdougie** [open-sauced/roadmap#2]
## Summary
This feature enables users to capture insights and share them on social and slack channels.

## Intended Outcome
Using this feature will enable team members to also capture and comment on insights within the OpenSauced insights platform. 

## How will it work?
Each insight dashboard will have a link they can copy to the clipboard and share as automated social cards. The social cards will be presented as infographics and interest from team members.

**Comment by getaheaddev** [comment]
Are these highlights? or insights? @bdougie ?

**Comment by getaheaddev** [comment]
Will this include data for the insights?
